apiVersion: v1
kind: Service
metadata:
  name: notejam-app-service
spec:

  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: notejam-k8s
  type: NodePort
  externalIPs:
    - 54.164.173.90

