apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notejam-k8s-stateful
  labels:
    app: notejam-k8s
spec:
  serviceName: notejam-k8s-ss
  replicas: 1
  selector:
    matchLabels:
      app: notejam-k8s
  template:
    metadata:
      labels:
        app: notejam-k8s
    spec:
      containers:
        - name: notejam-app
          image: nidaadocker/flask-app:v6
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/build/data/files"
              name: notejam-data
          env:
            - name: notejam-flask-secret-key
              valueFrom:
                secretKeyRef:
                  name: notejam-app-secrets
                  key: admin-password

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: notejam-app-secrets
                  key: db-endpoint
      volumes:
        - hostPath:
            path: "/home/docker/notejam-files"
          name: notejam-data
