apiVersion: apps/v1

kind: Deployment

metadata:

  name: postgres

spec:
  selector:
    matchLabels:
      service: postgres

  replicas: 1

  template:

    metadata:

      labels:

        service: postgres

    spec:

      containers:

        - name: postgres

          image: postgres:10.1

          ports:

            - containerPort: 5432

          env:

            - name: POSTGRES_DB

              value: db0

            - name: POSTGRES_USER

              value: notejam

            - name: POSTGRES_PASSWORD

              value: notejam

          volumeMounts:

            - mountPath: "/var/lib/postgresql/data"

              name: "notejam-pgdata"

      volumes:

        - hostPath:

            path: "/home/docker/pgdata"

          name: notejam-pgdata
